{
    "name": "trn Identifier",
    "version": "19.0.1.0.0",
    "category": "trn/Identity",
    "summary": "Typed external identifiers for partners",
    "author": "Your Organization",
    "website": "",
    "license": "LGPL-3",
    "development_status": "Alpha",
    "maintainers": [],
    "depends": ["trn_vocabulary"],
    "data": [
        "security/security_groups.xml",
        "security/ir.model.access.csv",
        "views/identifier_views.xml",
        "views/vocabulary_code_views.xml",
        "views/res_partner_views.xml",
        "views/menus.xml",
        "data/vocabulary_identifier_type.xml",
    ],
    "auto_install": False,
    "application": False,
    "installable": True,
}
